export const GET_CURRENCIES = 'GET_CURRENCIES';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const GET_CURRENCIES_SUCCEEDED = 'GET_CURRENCIES_SUCCEEDED';
export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';

export const REQUEST_CURRENCY_NAMES = 'REQUEST_CURRENCY_NAMES';
export const SUCCESS_CURRENCY_NAMES = 'SUCCESS_CURRENCY_NAMES';
export const FAILURE_CURRENCY_NAMES = 'FAILURE_CURRENCY_NAMES';

export const CHANGE_BALANCE = 'CHANGE_BALANCE';
export const REQUEST_QUOTATION = 'REQUEST_QUOTATION';
export const SUCCESS_QUOTATION = 'SUCCESS_QUOTATION';

export const REQUEST_CURRENCY_CONVERTED = 'REQUEST_CURRENCY_CONVERTED';
export const SUCCESS_CURRENCY_CONVERTED = 'SUCCESS_CURRENCY_CONVERTED';
export const LOADING_CONVERTED_CURRENCY_LIST = 'LOADING_CONVERTED_CURRENCY_LIST';
export const LOADED_CONVERTED_CURRENCY_LIST = 'LOADED_CONVERTED_CURRENCY_LIST';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const CHANGE_VALUE_SELECTED = 'CHANGE_VALUE_SELECTED';
export const CHANGE_VALUE_CONVERTED = 'CHANGE_VALUE_CONVERTED';
export const SELECT_CURRENCY_CONVERSION = 'SELECT_CURRENCY_CONVERSION';
export const SELECT_CURRENCY = 'SELECT_CURRENCY';
export const MOUNT_SELECT_CURRENCIES = 'MOUNT_SELECT_CURRENCIES';
export const CHANGE_VALUE_CONVERTED_FROM_COMBOBOX = 'CHANGE_VALUE_CONVERTED_FROM_COMBOBOX';
