export const GET_CURRENCIES = 'GET_CURRENCIES';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const GET_CURRENCIES_SUCCEEDED = 'GET_CURRENCIES_SUCCEEDED';

export const REQUEST_CURRENCY_NAMES = 'REQUEST_CURRENCY_NAMES';
export const SUCCESS_CURRENCY_NAMES = 'SUCCESS_CURRENCY_NAMES';
export const FAILURE_CURRENCY_NAMES = 'FAILURE_CURRENCY_NAMES';

export const CHANGE_BALANCE = 'CHANGE_BALANCE';
export const REQUEST_QUOTATION = 'REQUEST_QUOTATION';
export const SUCCESS_QUOTATION = 'SUCCESS_QUOTATION';

export const REQUEST_CURRENCY_CONVERTED = 'REQUEST_CURRENCY_CONVERTED';
export const SUCCESS_CURRENCY_CONVERTED = 'SUCCESS_CURRENCY_CONVERTED';
